
package org.phonebook.ws.sei.role;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RoleWSService", targetNamespace = "http://phonebook.org/ws", wsdlLocation = "http://localhost:8080/RoleWSService/RoleWS?wsdl")
public class RoleWSService
    extends Service
{

    private final static URL ROLEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROLEWSSERVICE_EXCEPTION;
    private final static QName ROLEWSSERVICE_QNAME = new QName("http://phonebook.org/ws", "RoleWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/RoleWSService/RoleWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROLEWSSERVICE_WSDL_LOCATION = url;
        ROLEWSSERVICE_EXCEPTION = e;
    }

    public RoleWSService() {
        super(__getWsdlLocation(), ROLEWSSERVICE_QNAME);
    }

    public RoleWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROLEWSSERVICE_QNAME, features);
    }

    public RoleWSService(URL wsdlLocation) {
        super(wsdlLocation, ROLEWSSERVICE_QNAME);
    }

    public RoleWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROLEWSSERVICE_QNAME, features);
    }

    public RoleWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RoleWS
     */
    @WebEndpoint(name = "RoleWSPort")
    public RoleWS getRoleWSPort() {
        return super.getPort(new QName("http://phonebook.org/ws", "RoleWSPort"), RoleWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoleWS
     */
    @WebEndpoint(name = "RoleWSPort")
    public RoleWS getRoleWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://phonebook.org/ws", "RoleWSPort"), RoleWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROLEWSSERVICE_EXCEPTION!= null) {
            throw ROLEWSSERVICE_EXCEPTION;
        }
        return ROLEWSSERVICE_WSDL_LOCATION;
    }

}
