
package org.phonebook.exceptions;

import javax.xml.ws.WebFault;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServiceException", targetNamespace = "http://phonebook.org/ws")
public class WSException
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceException faultInfo;
    
    /**
     * 
     */
    public WSException() {
        super();
    }

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WSException(String message, ServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WSException(String message, ServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.phonebook.ws.sei.user.ServiceException
     */
    public ServiceException getFaultInfo() {
        return faultInfo;
    }

}
